# Generated by Django 6.0.3 on 2026-04-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex07', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
