# Generated by Django 6.0.3 on 2026-04-01 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('climate', models.CharField()),
                ('diameter', models.IntegerField()),
                ('orbital_period', models.FloatField()),
                ('population', models.BigIntegerField()),
                ('rotation_period', models.IntegerField()),
                ('surface_water', models.FloatField()),
                ('terrain', models.CharField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ex09_planets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('birth_year', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=32)),
                ('eye_color', models.CharField(max_length=32)),
                ('hair_color', models.CharField(max_length=32)),
                ('height', models.IntegerField()),
                ('mass', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('homeworld', models.ForeignKey(blank=True, db_column='homeworld', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ex09.planets', to_field='name')),
            ],
            options={
                'db_table': 'ex09_people',
                'ordering': ['name'],
            },
        ),
    ]
