# Generated by Django 6.0.3 on 2026-04-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='population',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
