# Generated by Django 6.0.3 on 2026-04-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0002_alter_planets_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='birth_year',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='eye_color',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='gender',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='climate',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='diameter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='orbital_period',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='rotation_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='surface_water',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planets',
            name='terrain',
            field=models.CharField(blank=True, null=True),
        ),
    ]
