# Generated by Django 6.0.3 on 2026-04-01 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0003_alter_people_birth_year_alter_people_eye_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='homeworld',
            field=models.ForeignKey(blank=True, db_column='homeworld', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ex09.planets'),
        ),
    ]
