# Generated by Django 6.0.3 on 2026-04-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex03', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['episode_nb']},
        ),
    ]
