# Generated by Django 6.0.3 on 2026-04-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex02', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
