# Generated by Django 6.0.3 on 2026-04-02 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_tip_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.IntegerField(choices=[(1, 'Up'), (2, 'Down')])),
                ('author', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
                ('tip', models.ForeignKey(db_column='tip', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='app.tip')),
            ],
            options={
                'unique_together': {('tip', 'author')},
            },
        ),
    ]
