# Generated by Django 6.0.4 on 2026-04-21 13:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFavoriteArticle',
            new_name='UserFavouriteArticle',
        ),
    ]
