# Generated by Django 6.0.3 on 2026-04-01 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex10', '0002_remove_planets_created_remove_planets_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='created',
        ),
        migrations.RemoveField(
            model_name='people',
            name='updated',
        ),
    ]
