# Generated by Django 6.0.3 on 2026-04-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex10', '0003_remove_people_created_remove_people_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={},
        ),
        migrations.AlterModelOptions(
            name='planets',
            options={},
        ),
        migrations.AlterField(
            model_name='movies',
            name='characters',
            field=models.ManyToManyField(related_name='movies', to='ex10.people'),
        ),
    ]
